package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * AccountString generated by hbm2java
 */
public class AccountString implements java.io.Serializable {

	private AccountStringId id;
	private String singularTitle;
	private String pluralTitle;
	private String description;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public AccountString() {
	}

	public AccountString(AccountStringId id) {
		this.id = id;
	}

	public AccountString(AccountStringId id, String singularTitle,
			String pluralTitle, String description, Integer lastUpdateTime,
			Integer creationTime) {
		this.id = id;
		this.singularTitle = singularTitle;
		this.pluralTitle = pluralTitle;
		this.description = description;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public AccountStringId getId() {
		return this.id;
	}

	public void setId(AccountStringId id) {
		this.id = id;
	}

	public String getSingularTitle() {
		return this.singularTitle;
	}

	public void setSingularTitle(String singularTitle) {
		this.singularTitle = singularTitle;
	}

	public String getPluralTitle() {
		return this.pluralTitle;
	}

	public void setPluralTitle(String pluralTitle) {
		this.pluralTitle = pluralTitle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
