package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * DeviceGroup generated by hbm2java
 */
public class DeviceGroup implements java.io.Serializable {

	private DeviceGroupId id;
	private String displayName;
	private String description;
	private String notes;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public DeviceGroup() {
	}

	public DeviceGroup(DeviceGroupId id) {
		this.id = id;
	}

	public DeviceGroup(DeviceGroupId id, String displayName,
			String description, String notes, Integer lastUpdateTime,
			Integer creationTime) {
		this.id = id;
		this.displayName = displayName;
		this.description = description;
		this.notes = notes;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public DeviceGroupId getId() {
		return this.id;
	}

	public void setId(DeviceGroupId id) {
		this.id = id;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
