package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * DeviceList generated by hbm2java
 */
public class DeviceList implements java.io.Serializable {

	private DeviceListId id;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public DeviceList() {
	}

	public DeviceList(DeviceListId id) {
		this.id = id;
	}

	public DeviceList(DeviceListId id, Integer lastUpdateTime,
			Integer creationTime) {
		this.id = id;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public DeviceListId getId() {
		return this.id;
	}

	public void setId(DeviceListId id) {
		this.id = id;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
