package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private DeviceId id;
	private String groupId;
	private String equipmentType;
	private String equipmentStatus;
	private String vehicleMake;
	private String vehicleModel;
	private String vehicleId;
	private String licensePlate;
	private Integer licenseExpire;
	private Integer insuranceExpire;
	private String driverId;
	private Integer driverStatus;
	private Double fuelCapacity;
	private Double fuelEconomy;
	private Double fuelRatePerHour;
	private Double fuelCostPerLiter;
	private String fuelTankProfile;
	private Double speedLimitKph;
	private Double planDistanceKm;
	private Integer installTime;
	private Integer resetTime;
	private Integer expirationTime;
	private String uniqueId;
	private String deviceCode;
	private String deviceType;
	private String pushpinId;
	private String displayColor;
	private String serialNumber;
	private String simPhoneNumber;
	private String simId;
	private String smsEmail;
	private String imeiNumber;
	private String dataKey;
	private Short ignitionIndex;
	private String codeVersion;
	private String featureSet;
	private String ipAddressValid;
	private Integer lastTotalConnectTime;
	private Integer lastDuplexConnectTime;
	private String pendingPingCommand;
	private Integer lastPingTime;
	private Short totalPingCount;
	private Short maxPingCount;
	private Integer commandStateMask;
	private Byte expectAck;
	private Integer expectAckCode;
	private String lastAckCommand;
	private Integer lastAckTime;
	private String dcsPropertiesId;
	private Integer dcsConfigMask;
	private String dcsConfigString;
	private String dcsCommandHost;
	private Byte supportsDmtp;
	private Byte supportedEncodings;
	private Short unitLimitInterval;
	private Short maxAllowedEvents;
	private byte[] totalProfileMask;
	private Short totalMaxConn;
	private Short totalMaxConnPerMin;
	private byte[] duplexProfileMask;
	private Short duplexMaxConn;
	private Short duplexMaxConnPerMin;
	private String lastTcpSessionId;
	private String ipAddressCurrent;
	private Short remotePortCurrent;
	private Short listenPortCurrent;
	private Integer lastInputState;
	private Integer lastOutputState;
	private Integer statusCodeState;
	private Double lastBatteryLevel;
	private Double lastFuelLevel;
	private Double lastFuelTotal;
	private Double lastOilLevel;
	private Double lastValidLatitude;
	private Double lastValidLongitude;
	private Double lastValidHeading;
	private Double lastValidSpeedKph;
	private Integer lastGpstimestamp;
	private Integer lastEventTimestamp;
	private String lastCellServingInfo;
	private Double lastDistanceKm;
	private Double lastOdometerKm;
	private Double odometerOffsetKm;
	private Double lastEngineOnHours;
	private Integer lastEngineOnTime;
	private Integer lastEngineOffTime;
	private Double lastEngineHours;
	private Double engineHoursOffset;
	private Double lastIgnitionOnHours;
	private Integer lastIgnitionOnTime;
	private Integer lastIgnitionOffTime;
	private Double lastIgnitionHours;
	private Integer lastStopTime;
	private Integer lastStartTime;
	private Byte lastMalfunctionLamp;
	private String lastFaultCode;
	private Byte isActive;
	private String displayName;
	private String description;
	private String notes;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public Device() {
	}

	public Device(DeviceId id) {
		this.id = id;
	}

	public Device(DeviceId id, String groupId, String equipmentType,
			String equipmentStatus, String vehicleMake, String vehicleModel,
			String vehicleId, String licensePlate, Integer licenseExpire,
			Integer insuranceExpire, String driverId, Integer driverStatus,
			Double fuelCapacity, Double fuelEconomy, Double fuelRatePerHour,
			Double fuelCostPerLiter, String fuelTankProfile,
			Double speedLimitKph, Double planDistanceKm, Integer installTime,
			Integer resetTime, Integer expirationTime, String uniqueId,
			String deviceCode, String deviceType, String pushpinId,
			String displayColor, String serialNumber, String simPhoneNumber,
			String simId, String smsEmail, String imeiNumber, String dataKey,
			Short ignitionIndex, String codeVersion, String featureSet,
			String ipAddressValid, Integer lastTotalConnectTime,
			Integer lastDuplexConnectTime, String pendingPingCommand,
			Integer lastPingTime, Short totalPingCount, Short maxPingCount,
			Integer commandStateMask, Byte expectAck, Integer expectAckCode,
			String lastAckCommand, Integer lastAckTime, String dcsPropertiesId,
			Integer dcsConfigMask, String dcsConfigString,
			String dcsCommandHost, Byte supportsDmtp, Byte supportedEncodings,
			Short unitLimitInterval, Short maxAllowedEvents,
			byte[] totalProfileMask, Short totalMaxConn,
			Short totalMaxConnPerMin, byte[] duplexProfileMask,
			Short duplexMaxConn, Short duplexMaxConnPerMin,
			String lastTcpSessionId, String ipAddressCurrent,
			Short remotePortCurrent, Short listenPortCurrent,
			Integer lastInputState, Integer lastOutputState,
			Integer statusCodeState, Double lastBatteryLevel,
			Double lastFuelLevel, Double lastFuelTotal, Double lastOilLevel,
			Double lastValidLatitude, Double lastValidLongitude,
			Double lastValidHeading, Double lastValidSpeedKph,
			Integer lastGpstimestamp, Integer lastEventTimestamp,
			String lastCellServingInfo, Double lastDistanceKm,
			Double lastOdometerKm, Double odometerOffsetKm,
			Double lastEngineOnHours, Integer lastEngineOnTime,
			Integer lastEngineOffTime, Double lastEngineHours,
			Double engineHoursOffset, Double lastIgnitionOnHours,
			Integer lastIgnitionOnTime, Integer lastIgnitionOffTime,
			Double lastIgnitionHours, Integer lastStopTime,
			Integer lastStartTime, Byte lastMalfunctionLamp,
			String lastFaultCode, Byte isActive, String displayName,
			String description, String notes, Integer lastUpdateTime,
			Integer creationTime) {
		this.id = id;
		this.groupId = groupId;
		this.equipmentType = equipmentType;
		this.equipmentStatus = equipmentStatus;
		this.vehicleMake = vehicleMake;
		this.vehicleModel = vehicleModel;
		this.vehicleId = vehicleId;
		this.licensePlate = licensePlate;
		this.licenseExpire = licenseExpire;
		this.insuranceExpire = insuranceExpire;
		this.driverId = driverId;
		this.driverStatus = driverStatus;
		this.fuelCapacity = fuelCapacity;
		this.fuelEconomy = fuelEconomy;
		this.fuelRatePerHour = fuelRatePerHour;
		this.fuelCostPerLiter = fuelCostPerLiter;
		this.fuelTankProfile = fuelTankProfile;
		this.speedLimitKph = speedLimitKph;
		this.planDistanceKm = planDistanceKm;
		this.installTime = installTime;
		this.resetTime = resetTime;
		this.expirationTime = expirationTime;
		this.uniqueId = uniqueId;
		this.deviceCode = deviceCode;
		this.deviceType = deviceType;
		this.pushpinId = pushpinId;
		this.displayColor = displayColor;
		this.serialNumber = serialNumber;
		this.simPhoneNumber = simPhoneNumber;
		this.simId = simId;
		this.smsEmail = smsEmail;
		this.imeiNumber = imeiNumber;
		this.dataKey = dataKey;
		this.ignitionIndex = ignitionIndex;
		this.codeVersion = codeVersion;
		this.featureSet = featureSet;
		this.ipAddressValid = ipAddressValid;
		this.lastTotalConnectTime = lastTotalConnectTime;
		this.lastDuplexConnectTime = lastDuplexConnectTime;
		this.pendingPingCommand = pendingPingCommand;
		this.lastPingTime = lastPingTime;
		this.totalPingCount = totalPingCount;
		this.maxPingCount = maxPingCount;
		this.commandStateMask = commandStateMask;
		this.expectAck = expectAck;
		this.expectAckCode = expectAckCode;
		this.lastAckCommand = lastAckCommand;
		this.lastAckTime = lastAckTime;
		this.dcsPropertiesId = dcsPropertiesId;
		this.dcsConfigMask = dcsConfigMask;
		this.dcsConfigString = dcsConfigString;
		this.dcsCommandHost = dcsCommandHost;
		this.supportsDmtp = supportsDmtp;
		this.supportedEncodings = supportedEncodings;
		this.unitLimitInterval = unitLimitInterval;
		this.maxAllowedEvents = maxAllowedEvents;
		this.totalProfileMask = totalProfileMask;
		this.totalMaxConn = totalMaxConn;
		this.totalMaxConnPerMin = totalMaxConnPerMin;
		this.duplexProfileMask = duplexProfileMask;
		this.duplexMaxConn = duplexMaxConn;
		this.duplexMaxConnPerMin = duplexMaxConnPerMin;
		this.lastTcpSessionId = lastTcpSessionId;
		this.ipAddressCurrent = ipAddressCurrent;
		this.remotePortCurrent = remotePortCurrent;
		this.listenPortCurrent = listenPortCurrent;
		this.lastInputState = lastInputState;
		this.lastOutputState = lastOutputState;
		this.statusCodeState = statusCodeState;
		this.lastBatteryLevel = lastBatteryLevel;
		this.lastFuelLevel = lastFuelLevel;
		this.lastFuelTotal = lastFuelTotal;
		this.lastOilLevel = lastOilLevel;
		this.lastValidLatitude = lastValidLatitude;
		this.lastValidLongitude = lastValidLongitude;
		this.lastValidHeading = lastValidHeading;
		this.lastValidSpeedKph = lastValidSpeedKph;
		this.lastGpstimestamp = lastGpstimestamp;
		this.lastEventTimestamp = lastEventTimestamp;
		this.lastCellServingInfo = lastCellServingInfo;
		this.lastDistanceKm = lastDistanceKm;
		this.lastOdometerKm = lastOdometerKm;
		this.odometerOffsetKm = odometerOffsetKm;
		this.lastEngineOnHours = lastEngineOnHours;
		this.lastEngineOnTime = lastEngineOnTime;
		this.lastEngineOffTime = lastEngineOffTime;
		this.lastEngineHours = lastEngineHours;
		this.engineHoursOffset = engineHoursOffset;
		this.lastIgnitionOnHours = lastIgnitionOnHours;
		this.lastIgnitionOnTime = lastIgnitionOnTime;
		this.lastIgnitionOffTime = lastIgnitionOffTime;
		this.lastIgnitionHours = lastIgnitionHours;
		this.lastStopTime = lastStopTime;
		this.lastStartTime = lastStartTime;
		this.lastMalfunctionLamp = lastMalfunctionLamp;
		this.lastFaultCode = lastFaultCode;
		this.isActive = isActive;
		this.displayName = displayName;
		this.description = description;
		this.notes = notes;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public DeviceId getId() {
		return this.id;
	}

	public void setId(DeviceId id) {
		this.id = id;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	public String getEquipmentStatus() {
		return this.equipmentStatus;
	}

	public void setEquipmentStatus(String equipmentStatus) {
		this.equipmentStatus = equipmentStatus;
	}

	public String getVehicleMake() {
		return this.vehicleMake;
	}

	public void setVehicleMake(String vehicleMake) {
		this.vehicleMake = vehicleMake;
	}

	public String getVehicleModel() {
		return this.vehicleModel;
	}

	public void setVehicleModel(String vehicleModel) {
		this.vehicleModel = vehicleModel;
	}

	public String getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(String vehicleId) {
		this.vehicleId = vehicleId;
	}

	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public Integer getLicenseExpire() {
		return this.licenseExpire;
	}

	public void setLicenseExpire(Integer licenseExpire) {
		this.licenseExpire = licenseExpire;
	}

	public Integer getInsuranceExpire() {
		return this.insuranceExpire;
	}

	public void setInsuranceExpire(Integer insuranceExpire) {
		this.insuranceExpire = insuranceExpire;
	}

	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	public Integer getDriverStatus() {
		return this.driverStatus;
	}

	public void setDriverStatus(Integer driverStatus) {
		this.driverStatus = driverStatus;
	}

	public Double getFuelCapacity() {
		return this.fuelCapacity;
	}

	public void setFuelCapacity(Double fuelCapacity) {
		this.fuelCapacity = fuelCapacity;
	}

	public Double getFuelEconomy() {
		return this.fuelEconomy;
	}

	public void setFuelEconomy(Double fuelEconomy) {
		this.fuelEconomy = fuelEconomy;
	}

	public Double getFuelRatePerHour() {
		return this.fuelRatePerHour;
	}

	public void setFuelRatePerHour(Double fuelRatePerHour) {
		this.fuelRatePerHour = fuelRatePerHour;
	}

	public Double getFuelCostPerLiter() {
		return this.fuelCostPerLiter;
	}

	public void setFuelCostPerLiter(Double fuelCostPerLiter) {
		this.fuelCostPerLiter = fuelCostPerLiter;
	}

	public String getFuelTankProfile() {
		return this.fuelTankProfile;
	}

	public void setFuelTankProfile(String fuelTankProfile) {
		this.fuelTankProfile = fuelTankProfile;
	}

	public Double getSpeedLimitKph() {
		return this.speedLimitKph;
	}

	public void setSpeedLimitKph(Double speedLimitKph) {
		this.speedLimitKph = speedLimitKph;
	}

	public Double getPlanDistanceKm() {
		return this.planDistanceKm;
	}

	public void setPlanDistanceKm(Double planDistanceKm) {
		this.planDistanceKm = planDistanceKm;
	}

	public Integer getInstallTime() {
		return this.installTime;
	}

	public void setInstallTime(Integer installTime) {
		this.installTime = installTime;
	}

	public Integer getResetTime() {
		return this.resetTime;
	}

	public void setResetTime(Integer resetTime) {
		this.resetTime = resetTime;
	}

	public Integer getExpirationTime() {
		return this.expirationTime;
	}

	public void setExpirationTime(Integer expirationTime) {
		this.expirationTime = expirationTime;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getPushpinId() {
		return this.pushpinId;
	}

	public void setPushpinId(String pushpinId) {
		this.pushpinId = pushpinId;
	}

	public String getDisplayColor() {
		return this.displayColor;
	}

	public void setDisplayColor(String displayColor) {
		this.displayColor = displayColor;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getSimPhoneNumber() {
		return this.simPhoneNumber;
	}

	public void setSimPhoneNumber(String simPhoneNumber) {
		this.simPhoneNumber = simPhoneNumber;
	}

	public String getSimId() {
		return this.simId;
	}

	public void setSimId(String simId) {
		this.simId = simId;
	}

	public String getSmsEmail() {
		return this.smsEmail;
	}

	public void setSmsEmail(String smsEmail) {
		this.smsEmail = smsEmail;
	}

	public String getImeiNumber() {
		return this.imeiNumber;
	}

	public void setImeiNumber(String imeiNumber) {
		this.imeiNumber = imeiNumber;
	}

	public String getDataKey() {
		return this.dataKey;
	}

	public void setDataKey(String dataKey) {
		this.dataKey = dataKey;
	}

	public Short getIgnitionIndex() {
		return this.ignitionIndex;
	}

	public void setIgnitionIndex(Short ignitionIndex) {
		this.ignitionIndex = ignitionIndex;
	}

	public String getCodeVersion() {
		return this.codeVersion;
	}

	public void setCodeVersion(String codeVersion) {
		this.codeVersion = codeVersion;
	}

	public String getFeatureSet() {
		return this.featureSet;
	}

	public void setFeatureSet(String featureSet) {
		this.featureSet = featureSet;
	}

	public String getIpAddressValid() {
		return this.ipAddressValid;
	}

	public void setIpAddressValid(String ipAddressValid) {
		this.ipAddressValid = ipAddressValid;
	}

	public Integer getLastTotalConnectTime() {
		return this.lastTotalConnectTime;
	}

	public void setLastTotalConnectTime(Integer lastTotalConnectTime) {
		this.lastTotalConnectTime = lastTotalConnectTime;
	}

	public Integer getLastDuplexConnectTime() {
		return this.lastDuplexConnectTime;
	}

	public void setLastDuplexConnectTime(Integer lastDuplexConnectTime) {
		this.lastDuplexConnectTime = lastDuplexConnectTime;
	}

	public String getPendingPingCommand() {
		return this.pendingPingCommand;
	}

	public void setPendingPingCommand(String pendingPingCommand) {
		this.pendingPingCommand = pendingPingCommand;
	}

	public Integer getLastPingTime() {
		return this.lastPingTime;
	}

	public void setLastPingTime(Integer lastPingTime) {
		this.lastPingTime = lastPingTime;
	}

	public Short getTotalPingCount() {
		return this.totalPingCount;
	}

	public void setTotalPingCount(Short totalPingCount) {
		this.totalPingCount = totalPingCount;
	}

	public Short getMaxPingCount() {
		return this.maxPingCount;
	}

	public void setMaxPingCount(Short maxPingCount) {
		this.maxPingCount = maxPingCount;
	}

	public Integer getCommandStateMask() {
		return this.commandStateMask;
	}

	public void setCommandStateMask(Integer commandStateMask) {
		this.commandStateMask = commandStateMask;
	}

	public Byte getExpectAck() {
		return this.expectAck;
	}

	public void setExpectAck(Byte expectAck) {
		this.expectAck = expectAck;
	}

	public Integer getExpectAckCode() {
		return this.expectAckCode;
	}

	public void setExpectAckCode(Integer expectAckCode) {
		this.expectAckCode = expectAckCode;
	}

	public String getLastAckCommand() {
		return this.lastAckCommand;
	}

	public void setLastAckCommand(String lastAckCommand) {
		this.lastAckCommand = lastAckCommand;
	}

	public Integer getLastAckTime() {
		return this.lastAckTime;
	}

	public void setLastAckTime(Integer lastAckTime) {
		this.lastAckTime = lastAckTime;
	}

	public String getDcsPropertiesId() {
		return this.dcsPropertiesId;
	}

	public void setDcsPropertiesId(String dcsPropertiesId) {
		this.dcsPropertiesId = dcsPropertiesId;
	}

	public Integer getDcsConfigMask() {
		return this.dcsConfigMask;
	}

	public void setDcsConfigMask(Integer dcsConfigMask) {
		this.dcsConfigMask = dcsConfigMask;
	}

	public String getDcsConfigString() {
		return this.dcsConfigString;
	}

	public void setDcsConfigString(String dcsConfigString) {
		this.dcsConfigString = dcsConfigString;
	}

	public String getDcsCommandHost() {
		return this.dcsCommandHost;
	}

	public void setDcsCommandHost(String dcsCommandHost) {
		this.dcsCommandHost = dcsCommandHost;
	}

	public Byte getSupportsDmtp() {
		return this.supportsDmtp;
	}

	public void setSupportsDmtp(Byte supportsDmtp) {
		this.supportsDmtp = supportsDmtp;
	}

	public Byte getSupportedEncodings() {
		return this.supportedEncodings;
	}

	public void setSupportedEncodings(Byte supportedEncodings) {
		this.supportedEncodings = supportedEncodings;
	}

	public Short getUnitLimitInterval() {
		return this.unitLimitInterval;
	}

	public void setUnitLimitInterval(Short unitLimitInterval) {
		this.unitLimitInterval = unitLimitInterval;
	}

	public Short getMaxAllowedEvents() {
		return this.maxAllowedEvents;
	}

	public void setMaxAllowedEvents(Short maxAllowedEvents) {
		this.maxAllowedEvents = maxAllowedEvents;
	}

	public byte[] getTotalProfileMask() {
		return this.totalProfileMask;
	}

	public void setTotalProfileMask(byte[] totalProfileMask) {
		this.totalProfileMask = totalProfileMask;
	}

	public Short getTotalMaxConn() {
		return this.totalMaxConn;
	}

	public void setTotalMaxConn(Short totalMaxConn) {
		this.totalMaxConn = totalMaxConn;
	}

	public Short getTotalMaxConnPerMin() {
		return this.totalMaxConnPerMin;
	}

	public void setTotalMaxConnPerMin(Short totalMaxConnPerMin) {
		this.totalMaxConnPerMin = totalMaxConnPerMin;
	}

	public byte[] getDuplexProfileMask() {
		return this.duplexProfileMask;
	}

	public void setDuplexProfileMask(byte[] duplexProfileMask) {
		this.duplexProfileMask = duplexProfileMask;
	}

	public Short getDuplexMaxConn() {
		return this.duplexMaxConn;
	}

	public void setDuplexMaxConn(Short duplexMaxConn) {
		this.duplexMaxConn = duplexMaxConn;
	}

	public Short getDuplexMaxConnPerMin() {
		return this.duplexMaxConnPerMin;
	}

	public void setDuplexMaxConnPerMin(Short duplexMaxConnPerMin) {
		this.duplexMaxConnPerMin = duplexMaxConnPerMin;
	}

	public String getLastTcpSessionId() {
		return this.lastTcpSessionId;
	}

	public void setLastTcpSessionId(String lastTcpSessionId) {
		this.lastTcpSessionId = lastTcpSessionId;
	}

	public String getIpAddressCurrent() {
		return this.ipAddressCurrent;
	}

	public void setIpAddressCurrent(String ipAddressCurrent) {
		this.ipAddressCurrent = ipAddressCurrent;
	}

	public Short getRemotePortCurrent() {
		return this.remotePortCurrent;
	}

	public void setRemotePortCurrent(Short remotePortCurrent) {
		this.remotePortCurrent = remotePortCurrent;
	}

	public Short getListenPortCurrent() {
		return this.listenPortCurrent;
	}

	public void setListenPortCurrent(Short listenPortCurrent) {
		this.listenPortCurrent = listenPortCurrent;
	}

	public Integer getLastInputState() {
		return this.lastInputState;
	}

	public void setLastInputState(Integer lastInputState) {
		this.lastInputState = lastInputState;
	}

	public Integer getLastOutputState() {
		return this.lastOutputState;
	}

	public void setLastOutputState(Integer lastOutputState) {
		this.lastOutputState = lastOutputState;
	}

	public Integer getStatusCodeState() {
		return this.statusCodeState;
	}

	public void setStatusCodeState(Integer statusCodeState) {
		this.statusCodeState = statusCodeState;
	}

	public Double getLastBatteryLevel() {
		return this.lastBatteryLevel;
	}

	public void setLastBatteryLevel(Double lastBatteryLevel) {
		this.lastBatteryLevel = lastBatteryLevel;
	}

	public Double getLastFuelLevel() {
		return this.lastFuelLevel;
	}

	public void setLastFuelLevel(Double lastFuelLevel) {
		this.lastFuelLevel = lastFuelLevel;
	}

	public Double getLastFuelTotal() {
		return this.lastFuelTotal;
	}

	public void setLastFuelTotal(Double lastFuelTotal) {
		this.lastFuelTotal = lastFuelTotal;
	}

	public Double getLastOilLevel() {
		return this.lastOilLevel;
	}

	public void setLastOilLevel(Double lastOilLevel) {
		this.lastOilLevel = lastOilLevel;
	}

	public Double getLastValidLatitude() {
		return this.lastValidLatitude;
	}

	public void setLastValidLatitude(Double lastValidLatitude) {
		this.lastValidLatitude = lastValidLatitude;
	}

	public Double getLastValidLongitude() {
		return this.lastValidLongitude;
	}

	public void setLastValidLongitude(Double lastValidLongitude) {
		this.lastValidLongitude = lastValidLongitude;
	}

	public Double getLastValidHeading() {
		return this.lastValidHeading;
	}

	public void setLastValidHeading(Double lastValidHeading) {
		this.lastValidHeading = lastValidHeading;
	}

	public Double getLastValidSpeedKph() {
		return this.lastValidSpeedKph;
	}

	public void setLastValidSpeedKph(Double lastValidSpeedKph) {
		this.lastValidSpeedKph = lastValidSpeedKph;
	}

	public Integer getLastGpstimestamp() {
		return this.lastGpstimestamp;
	}

	public void setLastGpstimestamp(Integer lastGpstimestamp) {
		this.lastGpstimestamp = lastGpstimestamp;
	}

	public Integer getLastEventTimestamp() {
		return this.lastEventTimestamp;
	}

	public void setLastEventTimestamp(Integer lastEventTimestamp) {
		this.lastEventTimestamp = lastEventTimestamp;
	}

	public String getLastCellServingInfo() {
		return this.lastCellServingInfo;
	}

	public void setLastCellServingInfo(String lastCellServingInfo) {
		this.lastCellServingInfo = lastCellServingInfo;
	}

	public Double getLastDistanceKm() {
		return this.lastDistanceKm;
	}

	public void setLastDistanceKm(Double lastDistanceKm) {
		this.lastDistanceKm = lastDistanceKm;
	}

	public Double getLastOdometerKm() {
		return this.lastOdometerKm;
	}

	public void setLastOdometerKm(Double lastOdometerKm) {
		this.lastOdometerKm = lastOdometerKm;
	}

	public Double getOdometerOffsetKm() {
		return this.odometerOffsetKm;
	}

	public void setOdometerOffsetKm(Double odometerOffsetKm) {
		this.odometerOffsetKm = odometerOffsetKm;
	}

	public Double getLastEngineOnHours() {
		return this.lastEngineOnHours;
	}

	public void setLastEngineOnHours(Double lastEngineOnHours) {
		this.lastEngineOnHours = lastEngineOnHours;
	}

	public Integer getLastEngineOnTime() {
		return this.lastEngineOnTime;
	}

	public void setLastEngineOnTime(Integer lastEngineOnTime) {
		this.lastEngineOnTime = lastEngineOnTime;
	}

	public Integer getLastEngineOffTime() {
		return this.lastEngineOffTime;
	}

	public void setLastEngineOffTime(Integer lastEngineOffTime) {
		this.lastEngineOffTime = lastEngineOffTime;
	}

	public Double getLastEngineHours() {
		return this.lastEngineHours;
	}

	public void setLastEngineHours(Double lastEngineHours) {
		this.lastEngineHours = lastEngineHours;
	}

	public Double getEngineHoursOffset() {
		return this.engineHoursOffset;
	}

	public void setEngineHoursOffset(Double engineHoursOffset) {
		this.engineHoursOffset = engineHoursOffset;
	}

	public Double getLastIgnitionOnHours() {
		return this.lastIgnitionOnHours;
	}

	public void setLastIgnitionOnHours(Double lastIgnitionOnHours) {
		this.lastIgnitionOnHours = lastIgnitionOnHours;
	}

	public Integer getLastIgnitionOnTime() {
		return this.lastIgnitionOnTime;
	}

	public void setLastIgnitionOnTime(Integer lastIgnitionOnTime) {
		this.lastIgnitionOnTime = lastIgnitionOnTime;
	}

	public Integer getLastIgnitionOffTime() {
		return this.lastIgnitionOffTime;
	}

	public void setLastIgnitionOffTime(Integer lastIgnitionOffTime) {
		this.lastIgnitionOffTime = lastIgnitionOffTime;
	}

	public Double getLastIgnitionHours() {
		return this.lastIgnitionHours;
	}

	public void setLastIgnitionHours(Double lastIgnitionHours) {
		this.lastIgnitionHours = lastIgnitionHours;
	}

	public Integer getLastStopTime() {
		return this.lastStopTime;
	}

	public void setLastStopTime(Integer lastStopTime) {
		this.lastStopTime = lastStopTime;
	}

	public Integer getLastStartTime() {
		return this.lastStartTime;
	}

	public void setLastStartTime(Integer lastStartTime) {
		this.lastStartTime = lastStartTime;
	}

	public Byte getLastMalfunctionLamp() {
		return this.lastMalfunctionLamp;
	}

	public void setLastMalfunctionLamp(Byte lastMalfunctionLamp) {
		this.lastMalfunctionLamp = lastMalfunctionLamp;
	}

	public String getLastFaultCode() {
		return this.lastFaultCode;
	}

	public void setLastFaultCode(String lastFaultCode) {
		this.lastFaultCode = lastFaultCode;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
