package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * DeviceListId generated by hbm2java
 */
public class DeviceListId implements java.io.Serializable {

	private String accountId;
	private String groupId;
	private String deviceId;

	public DeviceListId() {
	}

	public DeviceListId(String accountId, String groupId, String deviceId) {
		this.accountId = accountId;
		this.groupId = groupId;
		this.deviceId = deviceId;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceListId))
			return false;
		DeviceListId castOther = (DeviceListId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null && castOther.getAccountId() != null && this
				.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getGroupId() == castOther.getGroupId()) || (this
						.getGroupId() != null && castOther.getGroupId() != null && this
						.getGroupId().equals(castOther.getGroupId())))
				&& ((this.getDeviceId() == castOther.getDeviceId()) || (this
						.getDeviceId() != null
						&& castOther.getDeviceId() != null && this
						.getDeviceId().equals(castOther.getDeviceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result
				+ (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		result = 37 * result
				+ (getDeviceId() == null ? 0 : this.getDeviceId().hashCode());
		return result;
	}

}
