package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * DiagnosticId generated by hbm2java
 */
public class DiagnosticId implements java.io.Serializable {

	private String accountId;
	private String deviceId;
	private byte isError;
	private int codeKey;
	private int timestamp;

	public DiagnosticId() {
	}

	public DiagnosticId(String accountId, String deviceId, byte isError,
			int codeKey, int timestamp) {
		this.accountId = accountId;
		this.deviceId = deviceId;
		this.isError = isError;
		this.codeKey = codeKey;
		this.timestamp = timestamp;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public byte getIsError() {
		return this.isError;
	}

	public void setIsError(byte isError) {
		this.isError = isError;
	}

	public int getCodeKey() {
		return this.codeKey;
	}

	public void setCodeKey(int codeKey) {
		this.codeKey = codeKey;
	}

	public int getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(int timestamp) {
		this.timestamp = timestamp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiagnosticId))
			return false;
		DiagnosticId castOther = (DiagnosticId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null && castOther.getAccountId() != null && this
				.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getDeviceId() == castOther.getDeviceId()) || (this
						.getDeviceId() != null
						&& castOther.getDeviceId() != null && this
						.getDeviceId().equals(castOther.getDeviceId())))
				&& (this.getIsError() == castOther.getIsError())
				&& (this.getCodeKey() == castOther.getCodeKey())
				&& (this.getTimestamp() == castOther.getTimestamp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result
				+ (getDeviceId() == null ? 0 : this.getDeviceId().hashCode());
		result = 37 * result + this.getIsError();
		result = 37 * result + this.getCodeKey();
		result = 37 * result + this.getTimestamp();
		return result;
	}

}
