package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * Diagnostic generated by hbm2java
 */
public class Diagnostic implements java.io.Serializable {

	private DiagnosticId id;
	private byte[] binaryValue;

	public Diagnostic() {
	}

	public Diagnostic(DiagnosticId id) {
		this.id = id;
	}

	public Diagnostic(DiagnosticId id, byte[] binaryValue) {
		this.id = id;
		this.binaryValue = binaryValue;
	}

	public DiagnosticId getId() {
		return this.id;
	}

	public void setId(DiagnosticId id) {
		this.id = id;
	}

	public byte[] getBinaryValue() {
		return this.binaryValue;
	}

	public void setBinaryValue(byte[] binaryValue) {
		this.binaryValue = binaryValue;
	}

}
