package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * Driver generated by hbm2java
 */
public class Driver implements java.io.Serializable {

	private DriverId id;
	private String contactPhone;
	private String contactEmail;
	private String licenseType;
	private String licenseNumber;
	private Integer licenseExpire;
	private String badgeId;
	private String address;
	private Integer birthdate;
	private String deviceId;
	private Integer driverStatus;
	private String displayName;
	private String description;
	private String notes;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public Driver() {
	}

	public Driver(DriverId id) {
		this.id = id;
	}

	public Driver(DriverId id, String contactPhone, String contactEmail,
			String licenseType, String licenseNumber, Integer licenseExpire,
			String badgeId, String address, Integer birthdate, String deviceId,
			Integer driverStatus, String displayName, String description,
			String notes, Integer lastUpdateTime, Integer creationTime) {
		this.id = id;
		this.contactPhone = contactPhone;
		this.contactEmail = contactEmail;
		this.licenseType = licenseType;
		this.licenseNumber = licenseNumber;
		this.licenseExpire = licenseExpire;
		this.badgeId = badgeId;
		this.address = address;
		this.birthdate = birthdate;
		this.deviceId = deviceId;
		this.driverStatus = driverStatus;
		this.displayName = displayName;
		this.description = description;
		this.notes = notes;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public DriverId getId() {
		return this.id;
	}

	public void setId(DriverId id) {
		this.id = id;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	public Integer getLicenseExpire() {
		return this.licenseExpire;
	}

	public void setLicenseExpire(Integer licenseExpire) {
		this.licenseExpire = licenseExpire;
	}

	public String getBadgeId() {
		return this.badgeId;
	}

	public void setBadgeId(String badgeId) {
		this.badgeId = badgeId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Integer birthdate) {
		this.birthdate = birthdate;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Integer getDriverStatus() {
		return this.driverStatus;
	}

	public void setDriverStatus(Integer driverStatus) {
		this.driverStatus = driverStatus;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
