package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * EventTemplate generated by hbm2java
 */
public class EventTemplate implements java.io.Serializable {

	private EventTemplateId id;
	private Byte repeatLast;
	private String template;

	public EventTemplate() {
	}

	public EventTemplate(EventTemplateId id) {
		this.id = id;
	}

	public EventTemplate(EventTemplateId id, Byte repeatLast, String template) {
		this.id = id;
		this.repeatLast = repeatLast;
		this.template = template;
	}

	public EventTemplateId getId() {
		return this.id;
	}

	public void setId(EventTemplateId id) {
		this.id = id;
	}

	public Byte getRepeatLast() {
		return this.repeatLast;
	}

	public void setRepeatLast(Byte repeatLast) {
		this.repeatLast = repeatLast;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

}
