package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * EventData generated by hbm2java
 */
public class EventData implements java.io.Serializable {

	private EventDataId id;
	private Double latitude;
	private Double longitude;
	private Integer gpsAge;
	private Double speedKph;
	private Double heading;
	private Double altitude;
	private String transportId;
	private Integer inputMask;
	private Integer outputMask;
	private Integer seatbeltMask;
	private String address;
	private String dataSource;
	private String rawData;
	private Double distanceKm;
	private Double odometerKm;
	private Double odometerOffsetKm;
	private Integer geozoneIndex;
	private String geozoneId;
	private Integer creationTime;

	public EventData() {
	}

	public EventData(EventDataId id) {
		this.id = id;
	}

	public EventData(EventDataId id, Double latitude, Double longitude,
			Integer gpsAge, Double speedKph, Double heading, Double altitude,
			String transportId, Integer inputMask, Integer outputMask,
			Integer seatbeltMask, String address, String dataSource,
			String rawData, Double distanceKm, Double odometerKm,
			Double odometerOffsetKm, Integer geozoneIndex, String geozoneId,
			Integer creationTime) {
		this.id = id;
		this.latitude = latitude;
		this.longitude = longitude;
		this.gpsAge = gpsAge;
		this.speedKph = speedKph;
		this.heading = heading;
		this.altitude = altitude;
		this.transportId = transportId;
		this.inputMask = inputMask;
		this.outputMask = outputMask;
		this.seatbeltMask = seatbeltMask;
		this.address = address;
		this.dataSource = dataSource;
		this.rawData = rawData;
		this.distanceKm = distanceKm;
		this.odometerKm = odometerKm;
		this.odometerOffsetKm = odometerOffsetKm;
		this.geozoneIndex = geozoneIndex;
		this.geozoneId = geozoneId;
		this.creationTime = creationTime;
	}

	public EventDataId getId() {
		return this.id;
	}

	public void setId(EventDataId id) {
		this.id = id;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Integer getGpsAge() {
		return this.gpsAge;
	}

	public void setGpsAge(Integer gpsAge) {
		this.gpsAge = gpsAge;
	}

	public Double getSpeedKph() {
		return this.speedKph;
	}

	public void setSpeedKph(Double speedKph) {
		this.speedKph = speedKph;
	}

	public Double getHeading() {
		return this.heading;
	}

	public void setHeading(Double heading) {
		this.heading = heading;
	}

	public Double getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	public String getTransportId() {
		return this.transportId;
	}

	public void setTransportId(String transportId) {
		this.transportId = transportId;
	}

	public Integer getInputMask() {
		return this.inputMask;
	}

	public void setInputMask(Integer inputMask) {
		this.inputMask = inputMask;
	}

	public Integer getOutputMask() {
		return this.outputMask;
	}

	public void setOutputMask(Integer outputMask) {
		this.outputMask = outputMask;
	}

	public Integer getSeatbeltMask() {
		return this.seatbeltMask;
	}

	public void setSeatbeltMask(Integer seatbeltMask) {
		this.seatbeltMask = seatbeltMask;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	public String getRawData() {
		return this.rawData;
	}

	public void setRawData(String rawData) {
		this.rawData = rawData;
	}

	public Double getDistanceKm() {
		return this.distanceKm;
	}

	public void setDistanceKm(Double distanceKm) {
		this.distanceKm = distanceKm;
	}

	public Double getOdometerKm() {
		return this.odometerKm;
	}

	public void setOdometerKm(Double odometerKm) {
		this.odometerKm = odometerKm;
	}

	public Double getOdometerOffsetKm() {
		return this.odometerOffsetKm;
	}

	public void setOdometerOffsetKm(Double odometerOffsetKm) {
		this.odometerOffsetKm = odometerOffsetKm;
	}

	public Integer getGeozoneIndex() {
		return this.geozoneIndex;
	}

	public void setGeozoneIndex(Integer geozoneIndex) {
		this.geozoneIndex = geozoneIndex;
	}

	public String getGeozoneId() {
		return this.geozoneId;
	}

	public void setGeozoneId(String geozoneId) {
		this.geozoneId = geozoneId;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
