package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * Geozone generated by hbm2java
 */
public class Geozone implements java.io.Serializable {

	private GeozoneId id;
	private Double minLatitude;
	private Double maxLatitude;
	private Double minLongitude;
	private Double maxLongitude;
	private String zonePurposeId;
	private Byte reverseGeocode;
	private Byte arrivalZone;
	private Byte departureZone;
	private Byte autoNotify;
	private Byte zoomRegion;
	private String shapeColor;
	private Byte zoneType;
	private Integer radius;
	private String vertices;
	private Double latitude1;
	private Double longitude1;
	private Double latitude2;
	private Double longitude2;
	private Double latitude3;
	private Double longitude3;
	private Double latitude4;
	private Double longitude4;
	private Double latitude5;
	private Double longitude5;
	private Double latitude6;
	private Double longitude6;
	private Double latitude7;
	private Double longitude7;
	private Double latitude8;
	private Double longitude8;
	private Double latitude9;
	private Double longitude9;
	private Double latitude10;
	private Double longitude10;
	private Byte clientUpload;
	private Integer clientId;
	private String groupId;
	private String streetAddress;
	private String city;
	private String stateProvince;
	private String postalCode;
	private String country;
	private String subdivision;
	private String contactPhone;
	private Byte isActive;
	private String displayName;
	private String description;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public Geozone() {
	}

	public Geozone(GeozoneId id) {
		this.id = id;
	}

	public Geozone(GeozoneId id, Double minLatitude, Double maxLatitude,
			Double minLongitude, Double maxLongitude, String zonePurposeId,
			Byte reverseGeocode, Byte arrivalZone, Byte departureZone,
			Byte autoNotify, Byte zoomRegion, String shapeColor, Byte zoneType,
			Integer radius, String vertices, Double latitude1,
			Double longitude1, Double latitude2, Double longitude2,
			Double latitude3, Double longitude3, Double latitude4,
			Double longitude4, Double latitude5, Double longitude5,
			Double latitude6, Double longitude6, Double latitude7,
			Double longitude7, Double latitude8, Double longitude8,
			Double latitude9, Double longitude9, Double latitude10,
			Double longitude10, Byte clientUpload, Integer clientId,
			String groupId, String streetAddress, String city,
			String stateProvince, String postalCode, String country,
			String subdivision, String contactPhone, Byte isActive,
			String displayName, String description, Integer lastUpdateTime,
			Integer creationTime) {
		this.id = id;
		this.minLatitude = minLatitude;
		this.maxLatitude = maxLatitude;
		this.minLongitude = minLongitude;
		this.maxLongitude = maxLongitude;
		this.zonePurposeId = zonePurposeId;
		this.reverseGeocode = reverseGeocode;
		this.arrivalZone = arrivalZone;
		this.departureZone = departureZone;
		this.autoNotify = autoNotify;
		this.zoomRegion = zoomRegion;
		this.shapeColor = shapeColor;
		this.zoneType = zoneType;
		this.radius = radius;
		this.vertices = vertices;
		this.latitude1 = latitude1;
		this.longitude1 = longitude1;
		this.latitude2 = latitude2;
		this.longitude2 = longitude2;
		this.latitude3 = latitude3;
		this.longitude3 = longitude3;
		this.latitude4 = latitude4;
		this.longitude4 = longitude4;
		this.latitude5 = latitude5;
		this.longitude5 = longitude5;
		this.latitude6 = latitude6;
		this.longitude6 = longitude6;
		this.latitude7 = latitude7;
		this.longitude7 = longitude7;
		this.latitude8 = latitude8;
		this.longitude8 = longitude8;
		this.latitude9 = latitude9;
		this.longitude9 = longitude9;
		this.latitude10 = latitude10;
		this.longitude10 = longitude10;
		this.clientUpload = clientUpload;
		this.clientId = clientId;
		this.groupId = groupId;
		this.streetAddress = streetAddress;
		this.city = city;
		this.stateProvince = stateProvince;
		this.postalCode = postalCode;
		this.country = country;
		this.subdivision = subdivision;
		this.contactPhone = contactPhone;
		this.isActive = isActive;
		this.displayName = displayName;
		this.description = description;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public GeozoneId getId() {
		return this.id;
	}

	public void setId(GeozoneId id) {
		this.id = id;
	}

	public Double getMinLatitude() {
		return this.minLatitude;
	}

	public void setMinLatitude(Double minLatitude) {
		this.minLatitude = minLatitude;
	}

	public Double getMaxLatitude() {
		return this.maxLatitude;
	}

	public void setMaxLatitude(Double maxLatitude) {
		this.maxLatitude = maxLatitude;
	}

	public Double getMinLongitude() {
		return this.minLongitude;
	}

	public void setMinLongitude(Double minLongitude) {
		this.minLongitude = minLongitude;
	}

	public Double getMaxLongitude() {
		return this.maxLongitude;
	}

	public void setMaxLongitude(Double maxLongitude) {
		this.maxLongitude = maxLongitude;
	}

	public String getZonePurposeId() {
		return this.zonePurposeId;
	}

	public void setZonePurposeId(String zonePurposeId) {
		this.zonePurposeId = zonePurposeId;
	}

	public Byte getReverseGeocode() {
		return this.reverseGeocode;
	}

	public void setReverseGeocode(Byte reverseGeocode) {
		this.reverseGeocode = reverseGeocode;
	}

	public Byte getArrivalZone() {
		return this.arrivalZone;
	}

	public void setArrivalZone(Byte arrivalZone) {
		this.arrivalZone = arrivalZone;
	}

	public Byte getDepartureZone() {
		return this.departureZone;
	}

	public void setDepartureZone(Byte departureZone) {
		this.departureZone = departureZone;
	}

	public Byte getAutoNotify() {
		return this.autoNotify;
	}

	public void setAutoNotify(Byte autoNotify) {
		this.autoNotify = autoNotify;
	}

	public Byte getZoomRegion() {
		return this.zoomRegion;
	}

	public void setZoomRegion(Byte zoomRegion) {
		this.zoomRegion = zoomRegion;
	}

	public String getShapeColor() {
		return this.shapeColor;
	}

	public void setShapeColor(String shapeColor) {
		this.shapeColor = shapeColor;
	}

	public Byte getZoneType() {
		return this.zoneType;
	}

	public void setZoneType(Byte zoneType) {
		this.zoneType = zoneType;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public String getVertices() {
		return this.vertices;
	}

	public void setVertices(String vertices) {
		this.vertices = vertices;
	}

	public Double getLatitude1() {
		return this.latitude1;
	}

	public void setLatitude1(Double latitude1) {
		this.latitude1 = latitude1;
	}

	public Double getLongitude1() {
		return this.longitude1;
	}

	public void setLongitude1(Double longitude1) {
		this.longitude1 = longitude1;
	}

	public Double getLatitude2() {
		return this.latitude2;
	}

	public void setLatitude2(Double latitude2) {
		this.latitude2 = latitude2;
	}

	public Double getLongitude2() {
		return this.longitude2;
	}

	public void setLongitude2(Double longitude2) {
		this.longitude2 = longitude2;
	}

	public Double getLatitude3() {
		return this.latitude3;
	}

	public void setLatitude3(Double latitude3) {
		this.latitude3 = latitude3;
	}

	public Double getLongitude3() {
		return this.longitude3;
	}

	public void setLongitude3(Double longitude3) {
		this.longitude3 = longitude3;
	}

	public Double getLatitude4() {
		return this.latitude4;
	}

	public void setLatitude4(Double latitude4) {
		this.latitude4 = latitude4;
	}

	public Double getLongitude4() {
		return this.longitude4;
	}

	public void setLongitude4(Double longitude4) {
		this.longitude4 = longitude4;
	}

	public Double getLatitude5() {
		return this.latitude5;
	}

	public void setLatitude5(Double latitude5) {
		this.latitude5 = latitude5;
	}

	public Double getLongitude5() {
		return this.longitude5;
	}

	public void setLongitude5(Double longitude5) {
		this.longitude5 = longitude5;
	}

	public Double getLatitude6() {
		return this.latitude6;
	}

	public void setLatitude6(Double latitude6) {
		this.latitude6 = latitude6;
	}

	public Double getLongitude6() {
		return this.longitude6;
	}

	public void setLongitude6(Double longitude6) {
		this.longitude6 = longitude6;
	}

	public Double getLatitude7() {
		return this.latitude7;
	}

	public void setLatitude7(Double latitude7) {
		this.latitude7 = latitude7;
	}

	public Double getLongitude7() {
		return this.longitude7;
	}

	public void setLongitude7(Double longitude7) {
		this.longitude7 = longitude7;
	}

	public Double getLatitude8() {
		return this.latitude8;
	}

	public void setLatitude8(Double latitude8) {
		this.latitude8 = latitude8;
	}

	public Double getLongitude8() {
		return this.longitude8;
	}

	public void setLongitude8(Double longitude8) {
		this.longitude8 = longitude8;
	}

	public Double getLatitude9() {
		return this.latitude9;
	}

	public void setLatitude9(Double latitude9) {
		this.latitude9 = latitude9;
	}

	public Double getLongitude9() {
		return this.longitude9;
	}

	public void setLongitude9(Double longitude9) {
		this.longitude9 = longitude9;
	}

	public Double getLatitude10() {
		return this.latitude10;
	}

	public void setLatitude10(Double latitude10) {
		this.latitude10 = latitude10;
	}

	public Double getLongitude10() {
		return this.longitude10;
	}

	public void setLongitude10(Double longitude10) {
		this.longitude10 = longitude10;
	}

	public Byte getClientUpload() {
		return this.clientUpload;
	}

	public void setClientUpload(Byte clientUpload) {
		this.clientUpload = clientUpload;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStateProvince() {
		return this.stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(String subdivision) {
		this.subdivision = subdivision;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
