package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * GeozoneId generated by hbm2java
 */
public class GeozoneId implements java.io.Serializable {

	private String accountId;
	private String geozoneId;
	private int sortId;

	public GeozoneId() {
	}

	public GeozoneId(String accountId, String geozoneId, int sortId) {
		this.accountId = accountId;
		this.geozoneId = geozoneId;
		this.sortId = sortId;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getGeozoneId() {
		return this.geozoneId;
	}

	public void setGeozoneId(String geozoneId) {
		this.geozoneId = geozoneId;
	}

	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GeozoneId))
			return false;
		GeozoneId castOther = (GeozoneId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null && castOther.getAccountId() != null && this
				.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getGeozoneId() == castOther.getGeozoneId()) || (this
						.getGeozoneId() != null
						&& castOther.getGeozoneId() != null && this
						.getGeozoneId().equals(castOther.getGeozoneId())))
				&& (this.getSortId() == castOther.getSortId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result
				+ (getGeozoneId() == null ? 0 : this.getGeozoneId().hashCode());
		result = 37 * result + this.getSortId();
		return result;
	}

}
