package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * GroupList generated by hbm2java
 */
public class GroupList implements java.io.Serializable {

	private GroupListId id;
	private Integer creationTime;

	public GroupList() {
	}

	public GroupList(GroupListId id) {
		this.id = id;
	}

	public GroupList(GroupListId id, Integer creationTime) {
		this.id = id;
		this.creationTime = creationTime;
	}

	public GroupListId getId() {
		return this.id;
	}

	public void setId(GroupListId id) {
		this.id = id;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
