package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * PendingPacket generated by hbm2java
 */
public class PendingPacket implements java.io.Serializable {

	private PendingPacketId id;
	private byte[] packetBytes;
	private Byte autoDelete;

	public PendingPacket() {
	}

	public PendingPacket(PendingPacketId id) {
		this.id = id;
	}

	public PendingPacket(PendingPacketId id, byte[] packetBytes, Byte autoDelete) {
		this.id = id;
		this.packetBytes = packetBytes;
		this.autoDelete = autoDelete;
	}

	public PendingPacketId getId() {
		return this.id;
	}

	public void setId(PendingPacketId id) {
		this.id = id;
	}

	public byte[] getPacketBytes() {
		return this.packetBytes;
	}

	public void setPacketBytes(byte[] packetBytes) {
		this.packetBytes = packetBytes;
	}

	public Byte getAutoDelete() {
		return this.autoDelete;
	}

	public void setAutoDelete(Byte autoDelete) {
		this.autoDelete = autoDelete;
	}

}
