package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * PendingPacketId generated by hbm2java
 */
public class PendingPacketId implements java.io.Serializable {

	private String accountId;
	private String deviceId;
	private int queueTime;
	private short sequence;

	public PendingPacketId() {
	}

	public PendingPacketId(String accountId, String deviceId, int queueTime,
			short sequence) {
		this.accountId = accountId;
		this.deviceId = deviceId;
		this.queueTime = queueTime;
		this.sequence = sequence;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public int getQueueTime() {
		return this.queueTime;
	}

	public void setQueueTime(int queueTime) {
		this.queueTime = queueTime;
	}

	public short getSequence() {
		return this.sequence;
	}

	public void setSequence(short sequence) {
		this.sequence = sequence;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PendingPacketId))
			return false;
		PendingPacketId castOther = (PendingPacketId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null && castOther.getAccountId() != null && this
				.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getDeviceId() == castOther.getDeviceId()) || (this
						.getDeviceId() != null
						&& castOther.getDeviceId() != null && this
						.getDeviceId().equals(castOther.getDeviceId())))
				&& (this.getQueueTime() == castOther.getQueueTime())
				&& (this.getSequence() == castOther.getSequence());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37 * result
				+ (getDeviceId() == null ? 0 : this.getDeviceId().hashCode());
		result = 37 * result + this.getQueueTime();
		result = 37 * result + this.getSequence();
		return result;
	}

}
