package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * Property generated by hbm2java
 */
public class Property implements java.io.Serializable {

	private PropertyId id;
	private Integer timestamp;
	private byte[] binaryValue;

	public Property() {
	}

	public Property(PropertyId id) {
		this.id = id;
	}

	public Property(PropertyId id, byte[] binaryValue) {
		this.id = id;
		this.binaryValue = binaryValue;
	}

	public PropertyId getId() {
		return this.id;
	}

	public void setId(PropertyId id) {
		this.id = id;
	}

	public Integer getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Integer timestamp) {
		this.timestamp = timestamp;
	}

	public byte[] getBinaryValue() {
		return this.binaryValue;
	}

	public void setBinaryValue(byte[] binaryValue) {
		this.binaryValue = binaryValue;
	}

}
