package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * SystemProps generated by hbm2java
 */
public class SystemProps implements java.io.Serializable {

	private String propertyId;
	private String dataType;
	private String value;
	private String description;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public SystemProps() {
	}

	public SystemProps(String propertyId) {
		this.propertyId = propertyId;
	}

	public SystemProps(String propertyId, String dataType, String value,
			String description, Integer lastUpdateTime, Integer creationTime) {
		this.propertyId = propertyId;
		this.dataType = dataType;
		this.value = value;
		this.description = description;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public String getPropertyId() {
		return this.propertyId;
	}

	public void setPropertyId(String propertyId) {
		this.propertyId = propertyId;
	}

	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
