package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * TransportId generated by hbm2java
 */
public class TransportId implements java.io.Serializable {

	private String accountId;
	private String transportId;

	public TransportId() {
	}

	public TransportId(String accountId, String transportId) {
		this.accountId = accountId;
		this.transportId = transportId;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getTransportId() {
		return this.transportId;
	}

	public void setTransportId(String transportId) {
		this.transportId = transportId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransportId))
			return false;
		TransportId castOther = (TransportId) other;

		return ((this.getAccountId() == castOther.getAccountId()) || (this
				.getAccountId() != null && castOther.getAccountId() != null && this
				.getAccountId().equals(castOther.getAccountId())))
				&& ((this.getTransportId() == castOther.getTransportId()) || (this
						.getTransportId() != null
						&& castOther.getTransportId() != null && this
						.getTransportId().equals(castOther.getTransportId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAccountId() == null ? 0 : this.getAccountId().hashCode());
		result = 37
				* result
				+ (getTransportId() == null ? 0 : this.getTransportId()
						.hashCode());
		return result;
	}

}
