package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * Transport generated by hbm2java
 */
public class Transport implements java.io.Serializable {

	private TransportId id;
	private String assocAccountId;
	private String assocDeviceId;
	private String uniqueId;
	private String deviceCode;
	private String deviceType;
	private String serialNumber;
	private String simPhoneNumber;
	private String smsEmail;
	private String imeiNumber;
	private Integer lastInputState;
	private Integer lastOutputState;
	private Short ignitionIndex;
	private String codeVersion;
	private String featureSet;
	private String ipAddressValid;
	private String ipAddressCurrent;
	private Short remotePortCurrent;
	private Short listenPortCurrent;
	private String pendingPingCommand;
	private Integer lastPingTime;
	private Short totalPingCount;
	private Short maxPingCount;
	private Byte expectAck;
	private String lastAckCommand;
	private Integer lastAckTime;
	private Byte supportsDmtp;
	private Byte supportedEncodings;
	private Short unitLimitInterval;
	private Short maxAllowedEvents;
	private byte[] totalProfileMask;
	private Short totalMaxConn;
	private Short totalMaxConnPerMin;
	private byte[] duplexProfileMask;
	private Short duplexMaxConn;
	private Short duplexMaxConnPerMin;
	private Integer lastTotalConnectTime;
	private Integer lastDuplexConnectTime;
	private String displayName;
	private String description;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public Transport() {
	}

	public Transport(TransportId id) {
		this.id = id;
	}

	public Transport(TransportId id, String assocAccountId,
			String assocDeviceId, String uniqueId, String deviceCode,
			String deviceType, String serialNumber, String simPhoneNumber,
			String smsEmail, String imeiNumber, Integer lastInputState,
			Integer lastOutputState, Short ignitionIndex, String codeVersion,
			String featureSet, String ipAddressValid, String ipAddressCurrent,
			Short remotePortCurrent, Short listenPortCurrent,
			String pendingPingCommand, Integer lastPingTime,
			Short totalPingCount, Short maxPingCount, Byte expectAck,
			String lastAckCommand, Integer lastAckTime, Byte supportsDmtp,
			Byte supportedEncodings, Short unitLimitInterval,
			Short maxAllowedEvents, byte[] totalProfileMask,
			Short totalMaxConn, Short totalMaxConnPerMin,
			byte[] duplexProfileMask, Short duplexMaxConn,
			Short duplexMaxConnPerMin, Integer lastTotalConnectTime,
			Integer lastDuplexConnectTime, String displayName,
			String description, Integer lastUpdateTime, Integer creationTime) {
		this.id = id;
		this.assocAccountId = assocAccountId;
		this.assocDeviceId = assocDeviceId;
		this.uniqueId = uniqueId;
		this.deviceCode = deviceCode;
		this.deviceType = deviceType;
		this.serialNumber = serialNumber;
		this.simPhoneNumber = simPhoneNumber;
		this.smsEmail = smsEmail;
		this.imeiNumber = imeiNumber;
		this.lastInputState = lastInputState;
		this.lastOutputState = lastOutputState;
		this.ignitionIndex = ignitionIndex;
		this.codeVersion = codeVersion;
		this.featureSet = featureSet;
		this.ipAddressValid = ipAddressValid;
		this.ipAddressCurrent = ipAddressCurrent;
		this.remotePortCurrent = remotePortCurrent;
		this.listenPortCurrent = listenPortCurrent;
		this.pendingPingCommand = pendingPingCommand;
		this.lastPingTime = lastPingTime;
		this.totalPingCount = totalPingCount;
		this.maxPingCount = maxPingCount;
		this.expectAck = expectAck;
		this.lastAckCommand = lastAckCommand;
		this.lastAckTime = lastAckTime;
		this.supportsDmtp = supportsDmtp;
		this.supportedEncodings = supportedEncodings;
		this.unitLimitInterval = unitLimitInterval;
		this.maxAllowedEvents = maxAllowedEvents;
		this.totalProfileMask = totalProfileMask;
		this.totalMaxConn = totalMaxConn;
		this.totalMaxConnPerMin = totalMaxConnPerMin;
		this.duplexProfileMask = duplexProfileMask;
		this.duplexMaxConn = duplexMaxConn;
		this.duplexMaxConnPerMin = duplexMaxConnPerMin;
		this.lastTotalConnectTime = lastTotalConnectTime;
		this.lastDuplexConnectTime = lastDuplexConnectTime;
		this.displayName = displayName;
		this.description = description;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public TransportId getId() {
		return this.id;
	}

	public void setId(TransportId id) {
		this.id = id;
	}

	public String getAssocAccountId() {
		return this.assocAccountId;
	}

	public void setAssocAccountId(String assocAccountId) {
		this.assocAccountId = assocAccountId;
	}

	public String getAssocDeviceId() {
		return this.assocDeviceId;
	}

	public void setAssocDeviceId(String assocDeviceId) {
		this.assocDeviceId = assocDeviceId;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getSimPhoneNumber() {
		return this.simPhoneNumber;
	}

	public void setSimPhoneNumber(String simPhoneNumber) {
		this.simPhoneNumber = simPhoneNumber;
	}

	public String getSmsEmail() {
		return this.smsEmail;
	}

	public void setSmsEmail(String smsEmail) {
		this.smsEmail = smsEmail;
	}

	public String getImeiNumber() {
		return this.imeiNumber;
	}

	public void setImeiNumber(String imeiNumber) {
		this.imeiNumber = imeiNumber;
	}

	public Integer getLastInputState() {
		return this.lastInputState;
	}

	public void setLastInputState(Integer lastInputState) {
		this.lastInputState = lastInputState;
	}

	public Integer getLastOutputState() {
		return this.lastOutputState;
	}

	public void setLastOutputState(Integer lastOutputState) {
		this.lastOutputState = lastOutputState;
	}

	public Short getIgnitionIndex() {
		return this.ignitionIndex;
	}

	public void setIgnitionIndex(Short ignitionIndex) {
		this.ignitionIndex = ignitionIndex;
	}

	public String getCodeVersion() {
		return this.codeVersion;
	}

	public void setCodeVersion(String codeVersion) {
		this.codeVersion = codeVersion;
	}

	public String getFeatureSet() {
		return this.featureSet;
	}

	public void setFeatureSet(String featureSet) {
		this.featureSet = featureSet;
	}

	public String getIpAddressValid() {
		return this.ipAddressValid;
	}

	public void setIpAddressValid(String ipAddressValid) {
		this.ipAddressValid = ipAddressValid;
	}

	public String getIpAddressCurrent() {
		return this.ipAddressCurrent;
	}

	public void setIpAddressCurrent(String ipAddressCurrent) {
		this.ipAddressCurrent = ipAddressCurrent;
	}

	public Short getRemotePortCurrent() {
		return this.remotePortCurrent;
	}

	public void setRemotePortCurrent(Short remotePortCurrent) {
		this.remotePortCurrent = remotePortCurrent;
	}

	public Short getListenPortCurrent() {
		return this.listenPortCurrent;
	}

	public void setListenPortCurrent(Short listenPortCurrent) {
		this.listenPortCurrent = listenPortCurrent;
	}

	public String getPendingPingCommand() {
		return this.pendingPingCommand;
	}

	public void setPendingPingCommand(String pendingPingCommand) {
		this.pendingPingCommand = pendingPingCommand;
	}

	public Integer getLastPingTime() {
		return this.lastPingTime;
	}

	public void setLastPingTime(Integer lastPingTime) {
		this.lastPingTime = lastPingTime;
	}

	public Short getTotalPingCount() {
		return this.totalPingCount;
	}

	public void setTotalPingCount(Short totalPingCount) {
		this.totalPingCount = totalPingCount;
	}

	public Short getMaxPingCount() {
		return this.maxPingCount;
	}

	public void setMaxPingCount(Short maxPingCount) {
		this.maxPingCount = maxPingCount;
	}

	public Byte getExpectAck() {
		return this.expectAck;
	}

	public void setExpectAck(Byte expectAck) {
		this.expectAck = expectAck;
	}

	public String getLastAckCommand() {
		return this.lastAckCommand;
	}

	public void setLastAckCommand(String lastAckCommand) {
		this.lastAckCommand = lastAckCommand;
	}

	public Integer getLastAckTime() {
		return this.lastAckTime;
	}

	public void setLastAckTime(Integer lastAckTime) {
		this.lastAckTime = lastAckTime;
	}

	public Byte getSupportsDmtp() {
		return this.supportsDmtp;
	}

	public void setSupportsDmtp(Byte supportsDmtp) {
		this.supportsDmtp = supportsDmtp;
	}

	public Byte getSupportedEncodings() {
		return this.supportedEncodings;
	}

	public void setSupportedEncodings(Byte supportedEncodings) {
		this.supportedEncodings = supportedEncodings;
	}

	public Short getUnitLimitInterval() {
		return this.unitLimitInterval;
	}

	public void setUnitLimitInterval(Short unitLimitInterval) {
		this.unitLimitInterval = unitLimitInterval;
	}

	public Short getMaxAllowedEvents() {
		return this.maxAllowedEvents;
	}

	public void setMaxAllowedEvents(Short maxAllowedEvents) {
		this.maxAllowedEvents = maxAllowedEvents;
	}

	public byte[] getTotalProfileMask() {
		return this.totalProfileMask;
	}

	public void setTotalProfileMask(byte[] totalProfileMask) {
		this.totalProfileMask = totalProfileMask;
	}

	public Short getTotalMaxConn() {
		return this.totalMaxConn;
	}

	public void setTotalMaxConn(Short totalMaxConn) {
		this.totalMaxConn = totalMaxConn;
	}

	public Short getTotalMaxConnPerMin() {
		return this.totalMaxConnPerMin;
	}

	public void setTotalMaxConnPerMin(Short totalMaxConnPerMin) {
		this.totalMaxConnPerMin = totalMaxConnPerMin;
	}

	public byte[] getDuplexProfileMask() {
		return this.duplexProfileMask;
	}

	public void setDuplexProfileMask(byte[] duplexProfileMask) {
		this.duplexProfileMask = duplexProfileMask;
	}

	public Short getDuplexMaxConn() {
		return this.duplexMaxConn;
	}

	public void setDuplexMaxConn(Short duplexMaxConn) {
		this.duplexMaxConn = duplexMaxConn;
	}

	public Short getDuplexMaxConnPerMin() {
		return this.duplexMaxConnPerMin;
	}

	public void setDuplexMaxConnPerMin(Short duplexMaxConnPerMin) {
		this.duplexMaxConnPerMin = duplexMaxConnPerMin;
	}

	public Integer getLastTotalConnectTime() {
		return this.lastTotalConnectTime;
	}

	public void setLastTotalConnectTime(Integer lastTotalConnectTime) {
		this.lastTotalConnectTime = lastTotalConnectTime;
	}

	public Integer getLastDuplexConnectTime() {
		return this.lastDuplexConnectTime;
	}

	public void setLastDuplexConnectTime(Integer lastDuplexConnectTime) {
		this.lastDuplexConnectTime = lastDuplexConnectTime;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
