package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * UniqueXid generated by hbm2java
 */
public class UniqueXid implements java.io.Serializable {

	private String uniqueId;
	private String accountId;
	private String transportId;

	public UniqueXid() {
	}

	public UniqueXid(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public UniqueXid(String uniqueId, String accountId, String transportId) {
		this.uniqueId = uniqueId;
		this.accountId = accountId;
		this.transportId = transportId;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getTransportId() {
		return this.transportId;
	}

	public void setTransportId(String transportId) {
		this.transportId = transportId;
	}

}
