package com.jiesoft.mitrac.domain.bo;

// Generated 18/06/2015 4:40:44 PM by Hibernate Tools 4.3.1

/**
 * UserAcl generated by hbm2java
 */
public class UserAcl implements java.io.Serializable {

	private UserAclId id;
	private Short accessLevel;
	private String description;
	private Integer lastUpdateTime;
	private Integer creationTime;

	public UserAcl() {
	}

	public UserAcl(UserAclId id) {
		this.id = id;
	}

	public UserAcl(UserAclId id, Short accessLevel, String description,
			Integer lastUpdateTime, Integer creationTime) {
		this.id = id;
		this.accessLevel = accessLevel;
		this.description = description;
		this.lastUpdateTime = lastUpdateTime;
		this.creationTime = creationTime;
	}

	public UserAclId getId() {
		return this.id;
	}

	public void setId(UserAclId id) {
		this.id = id;
	}

	public Short getAccessLevel() {
		return this.accessLevel;
	}

	public void setAccessLevel(Short accessLevel) {
		this.accessLevel = accessLevel;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Integer lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	public Integer getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Integer creationTime) {
		this.creationTime = creationTime;
	}

}
